[package]
name    = "tinybit-tests"
version = "0.1.0"
edition = "2021"
publish = false

[dev-dependencies]
tinybit-core  = { path = "../crates/tinybit-core" }
tinybit-tools = { path = "../crates/tinybit-tools" }
tinybit-train = { path = "../crates/tinybit-train" }
candle-core    = { workspace = true }
candle-nn      = { workspace = true }
anyhow         = { workspace = true }
rand           = { workspace = true }
