vocab_size  = 32008
num_layers  = 32
d_model     = 1024
d_ffn       = 2048
num_heads   = 16
head_dim    = 64
max_seq_len = 2048
dropout     = 0.05
spec_heads  = 3
ternary_ffn = false
int8_time   = false
