vocab_size  = 32008
num_layers  = 16
d_model     = 384
d_ffn       = 1344
num_heads   = 6
head_dim    = 64
max_seq_len = 512
dropout     = 0.05
spec_heads  = 0
ternary_ffn = false
int8_time   = false
