vocab_size  = 32008
num_layers  = 12
d_model     = 320
d_ffn       = 640
num_heads   = 5
head_dim    = 64
max_seq_len = 1024
dropout     = 0.05
spec_heads  = 0
ternary_ffn = false
int8_time   = false
