vocab_size  = 32008
num_layers  = 12
d_model     = 640
d_ffn       = 2240
num_heads   = 10
head_dim    = 64
max_seq_len = 1024
dropout     = 0.05
spec_heads  = 0
ternary_ffn = false
int8_time   = false
